apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-tnbn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-tnbn
    app.kubernetes.io/part-of: tkrw-pr712-0075-0063-app
  name: devfile-sample-tnbn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-tnbn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-tnbn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-tnbn@sha256:31bde180dbf883f9e64667beef1f025036740b9c9bcfcb2f1bbcfbef7b4d629e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
